/**
 * Typed client for the Neo Learn API.
 *
 * Every call sends credentials so the session cookie travels with it. There is
 * no token in a header or in local storage: an XSS bug would then hand over
 * the session directly rather than requiring the attacker to also ride the
 * user's session.
 */

import type {
  ApiErrorBody,
  Assessment,
  Course,
  CourseProgress,
  EventKind,
  EventSource,
  IngestResponse,
  Lesson,
  Module,
  User,
} from './types'

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:8080'

/**
 * ApiError carries the server's machine-readable code so callers can branch on
 * the failure without string-matching the message.
 */
export class ApiError extends Error {
  readonly status: number
  readonly code: string
  readonly details: Record<string, string>

  constructor(status: number, body: ApiErrorBody) {
    super(body.error)
    this.name = 'ApiError'
    this.status = status
    this.code = body.code
    this.details = body.details ?? {}
  }

  /** True when the request failed because nobody is signed in. */
  get isUnauthenticated(): boolean {
    return this.status === 401
  }

  /** True when the network could not be reached at all. */
  get isNetworkError(): boolean {
    return this.status === 0
  }
}

interface RequestOptions {
  readonly method?: 'GET' | 'POST'
  readonly body?: unknown
  readonly signal?: AbortSignal
}

async function request<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const { method = 'GET', body, signal } = options

  let response: Response
  try {
    response = await fetch(`${API_BASE_URL}${path}`, {
      method,
      // Required for the session cookie to be stored and sent.
      credentials: 'include',
      signal,
      headers: body === undefined ? {} : { 'Content-Type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
  } catch (cause) {
    if (cause instanceof DOMException && cause.name === 'AbortError') {
      throw cause
    }
    // Status 0 marks this as a transport failure, distinct from any HTTP
    // status. The offline queue keys off it.
    throw new ApiError(0, {
      error: 'Could not reach the Neo Learn server.',
      code: 'network_error',
    })
  }

  if (response.status === 204) {
    return undefined as T
  }

  const raw = await response.text()
  let parsed: unknown
  try {
    parsed = raw === '' ? undefined : JSON.parse(raw)
  } catch {
    throw new ApiError(response.status, {
      error: 'The server returned a response that could not be read.',
      code: 'invalid_response',
    })
  }

  if (!response.ok) {
    const body = parsed as Partial<ApiErrorBody> | undefined
    throw new ApiError(
      response.status,
      body && typeof body.error === 'string'
        ? { error: body.error, code: body.code ?? 'unknown', details: body.details }
        : { error: `Request failed with status ${response.status}.`, code: 'unknown' },
    )
  }

  return parsed as T
}

export const api = {
  login(institution: string, email: string, password: string): Promise<User> {
    return request<User>('/v1/auth/login', {
      method: 'POST',
      body: { institution, email, password },
    })
  },

  logout(): Promise<void> {
    return request<void>('/v1/auth/logout', { method: 'POST', body: {} })
  },

  me(signal?: AbortSignal): Promise<User> {
    return request<User>('/v1/me', signal ? { signal } : {})
  },

  courses(signal?: AbortSignal): Promise<{ courses: Course[] }> {
    return request<{ courses: Course[] }>('/v1/courses', signal ? { signal } : {})
  },

  courseModules(courseId: number, signal?: AbortSignal): Promise<{ modules: Module[] }> {
    return request<{ modules: Module[] }>(
      `/v1/courses/${courseId}/lessons`,
      signal ? { signal } : {},
    )
  },

  lesson(lessonId: number, signal?: AbortSignal): Promise<Lesson> {
    return request<Lesson>(`/v1/lessons/${lessonId}`, signal ? { signal } : {})
  },

  assessments(courseId: number, signal?: AbortSignal): Promise<{ assessments: Assessment[] }> {
    return request<{ assessments: Assessment[] }>(
      `/v1/courses/${courseId}/assessments`,
      signal ? { signal } : {},
    )
  },

  assessment(assessmentId: number, signal?: AbortSignal): Promise<Assessment> {
    return request<Assessment>(`/v1/assessments/${assessmentId}`, signal ? { signal } : {})
  },

  progress(signal?: AbortSignal): Promise<{ courses: CourseProgress[] }> {
    return request<{ courses: CourseProgress[] }>('/v1/progress', signal ? { signal } : {})
  },

  /**
   * Submits one learner action.
   *
   * `eventId` must be generated by the caller and must be stable across
   * retries. That is what makes a duplicate submission harmless, whether it
   * comes from a double-click or from the offline queue replaying.
   */
  ingestEvent(input: {
    eventId: string
    kind: EventKind
    source?: EventSource
    lessonId?: number
    assessmentId?: number
    questionId?: number
    choiceLabel?: string
    occurredAt?: string
    /** Caller-supplied deadline; combined with any outer signal. */
    signal?: AbortSignal
  }): Promise<IngestResponse> {
    return request<IngestResponse>('/v1/events', {
      method: 'POST',
      signal: input.signal,
      body: {
        event_id: input.eventId,
        kind: input.kind,
        source: input.source ?? 'web',
        lesson_id: input.lessonId,
        assessment_id: input.assessmentId,
        question_id: input.questionId,
        choice_label: input.choiceLabel,
        occurred_at: input.occurredAt,
      },
    })
  },
} as const

/**
 * Generates the client-side idempotency key for an event.
 *
 * crypto.randomUUID is used rather than a counter so that two devices, or two
 * tabs, cannot mint the same key: the uniqueness constraint on event_id is
 * global, so a predictable id would let one learner's action be swallowed by
 * another's.
 */
export function newEventId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }
  // Only reached on an insecure origin, where crypto.randomUUID is absent.
  // Not cryptographically random, but the value only has to be unique, and
  // the server's constraint is what actually enforces that.
  const random = Math.random().toString(36).slice(2)
  return `xxxxxxxx-xxxx-4xxx-yxxx-${random}`.replace(/[xy]/g, (c) => {
    const r = Math.floor(Math.random() * 16)
    const v = c === 'x' ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}