// Package learning implements the transport-independent learning engine.
//
// Nothing in this package knows about HTTP, SMS, or SIM Toolkit. It accepts a
// learner action and applies it to learner state. Adding a transport means
// calling Ingest; it does not mean changing anything here.
//
// # The event log
//
// Every state change arrives as a LearningEvent carrying a client-generated
// EventID. That ID is the idempotency key. A learner who texts the same answer
// twice, or a mobile client whose offline queue replays after a flaky
// reconnect, produces the same ID, and the second attempt is discarded.
//
// This is why there is no dedupe table and no conflict resolution here: an
// append-only log with a unique key admits one history, and duplicates never
// reach the projection.
//
// # The projection
//
// Progress rows are a materialized view of the log, maintained in the same
// transaction as the event that caused them. They exist so a dashboard read is
// one indexed lookup instead of an aggregate over the whole log. They are
// disposable: rebuilding progress from learning_events is a pure function of
// the log.
package learning

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/neolearn/neolearn/internal/db"
)

// Sentinel errors mapped to HTTP status codes by the transport layer.
var (
	ErrEventIDRequired  = errors.New("learning: event_id is required")
	ErrEventIDInvalid   = errors.New("learning: event_id must be a UUID")
	ErrKindRequired     = errors.New("learning: kind is required")
	ErrKindInvalid      = errors.New("learning: unknown event kind")
	ErrSourceInvalid    = errors.New("learning: unknown event source")
	ErrLearnerRequired  = errors.New("learning: learner_id is required")
	ErrChoiceRequired   = errors.New("learning: choice_label is required for question_answered")
	ErrQuestionRequired = errors.New("learning: question_id is required for question_answered")
	ErrLessonRequired   = errors.New("learning: lesson_id is required for lesson events")
	ErrChoiceNotFound   = errors.New("learning: choice not found for question")
	ErrQuestionNotFound = errors.New("learning: question not found")
	ErrCourseIDRequired = errors.New("learning: course_id could not be resolved for the event")
)

// Kind is a learning event type. Mirrors the event_kind Postgres enum.
type Kind string

const (
	KindLessonStarted       Kind = "lesson_started"
	KindLessonCompleted     Kind = "lesson_completed"
	KindQuestionAnswered    Kind = "question_answered"
	KindAssessmentSubmitted Kind = "assessment_submitted"
)

// Source identifies the transport an event arrived on. Mirrors event_source.
type Source string

const (
	SourceWeb Source = "web"
	SourceSMS Source = "sms"
	SourceSTK Source = "stk"
)

// IsValid reports whether k is a known event kind.
func (k Kind) IsValid() bool {
	switch k {
	case KindLessonStarted, KindLessonCompleted, KindQuestionAnswered, KindAssessmentSubmitted:
		return true
	}
	return false
}

// IsValid reports whether s is a known transport.
func (s Source) IsValid() bool {
	switch s {
	case SourceWeb, SourceSMS, SourceSTK:
		return true
	}
	return false
}

// AnswerPayload is the payload for a question_answered event.
type AnswerPayload struct {
	ChoiceLabel string `json:"choice_label"`
}

// Event is a learner action submitted to the engine.
//
// EventID must be generated by the client, not the server. That is what makes
// the operation idempotent: the client can retry a request it never saw the
// response to, and the server recognizes the second attempt.
type Event struct {
	EventID       uuid.UUID
	InstitutionID int64
	LearnerID     int64
	CourseID      *int64
	LessonID      *int64
	AssessmentID  *int64
	QuestionID    *int64
	Kind          Kind
	Source        Source
	Payload       json.RawMessage
	// OccurredAt is the learner's clock. It may be hours before ReceivedAt
	// when the event arrives from the offline queue or an SMS reply.
	OccurredAt time.Time
}

// Result is the outcome of ingesting an event.
type Result struct {
	EventID uuid.UUID
	// Duplicate is true when this exact event had already been recorded, in
	// which case the projection was left untouched and no progress changed.
	Duplicate bool
	// Graded carries the outcome of a question_answered event, absent for
	// other kinds.
	Graded *GradedAnswer
}

// GradedAnswer is the authoritative verdict for a submitted answer.
//
// The client is shown this after submitting, but it is computed server-side:
// an SMS learner has no way to be trusted to grade themselves.
type GradedAnswer struct {
	QuestionID  int64
	ChoiceLabel string
	Correct     bool
	Marks       int32
	// MarksAwarded is the marks earned, zero when incorrect.
	MarksAwarded int32
	MarksTotal   int32
	Percent      int32
}

// Service is the learning engine.
type Service struct {
	queries *db.Queries
	// pool is held so Ingest can open its own transaction. Every write to the
	// log, the projection, and the outbox must be atomic; sharing one
	// connection across goroutines would not be.
	pool *pgxpool.Pool
}

// NewService constructs the engine.
func NewService(pool *pgxpool.Pool, queries *db.Queries) *Service {
	return &Service{pool: pool, queries: queries}
}

// Ingest records an event and updates the projection atomically.
//
// Idempotent on EventID. A duplicate returns Result{Duplicate: true} and
// changes nothing, so a learner who answers twice is scored once.
func (s *Service) Ingest(ctx context.Context, ev Event) (Result, error) {
	if err := ev.validate(); err != nil {
		return Result{}, err
	}
	if ev.OccurredAt.IsZero() {
		ev.OccurredAt = time.Now().UTC()
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Result{}, fmt.Errorf("learning: begin transaction: %w", err)
	}
	// Rollback after a successful Commit is a no-op, so this is safe to defer
	// unconditionally rather than tracking a committed flag.
	defer func() { _ = tx.Rollback(ctx) }()

	queries := s.queries.WithTx(tx)

	inserted, err := queries.InsertLearningEvent(ctx, db.InsertLearningEventParams{
		EventID:       uuidParam(ev.EventID),
		InstitutionID: ev.InstitutionID,
		LearnerID:     ev.LearnerID,
		CourseID:      ev.CourseID,
		LessonID:      ev.LessonID,
		AssessmentID:  ev.AssessmentID,
		QuestionID:    ev.QuestionID,
		Kind:          db.EventKind(ev.Kind),
		Source:        db.EventSource(ev.Source),
		Payload:       []byte(ev.Payload),
		OccurredAt:    ev.OccurredAt,
	})
	if err != nil {
		return Result{}, fmt.Errorf("learning: insert event: %w", err)
	}

	if inserted.ID == 0 {
		// ON CONFLICT DO NOTHING returned no row: we have seen this event
		// before. The projection already reflects it.
		//
		// Returning Duplicate without touching progress is the whole
		// idempotency contract. Note this does not re-send a notification,
		// so a duplicate SMS does not produce a second acknowledgement --
		// which is exactly what the learner who pressed "send" twice wants.
		return Result{EventID: ev.EventID, Duplicate: true}, nil
	}

	result := Result{EventID: ev.EventID}

	switch ev.Kind {
	case KindQuestionAnswered:
		graded, err := s.applyAnswer(ctx, queries, ev)
		if err != nil {
			return Result{}, err
		}
		result.Graded = &graded

	case KindLessonStarted, KindLessonCompleted:
		if err := s.applyLessonProgress(ctx, queries, ev); err != nil {
			return Result{}, err
		}

	case KindAssessmentSubmitted:
		// Submitted-ness is implied by the answers recorded against the
		// assessment, so there is nothing further to project. The row exists
		// in the log for audit and for the SMS acknowledgement in M2.
	}

	if err := s.enqueueNotification(ctx, queries, ev); err != nil {
		return Result{}, err
	}

	if err := tx.Commit(ctx); err != nil {
		return Result{}, fmt.Errorf("learning: commit: %w", err)
	}

	return result, nil
}

// applyAnswer grades an answer and folds it into the assessment projection.
func (s *Service) applyAnswer(ctx context.Context, queries *db.Queries, ev Event) (GradedAnswer, error) {
	var payload AnswerPayload
	if len(ev.Payload) > 0 {
		if err := json.Unmarshal(ev.Payload, &payload); err != nil {
			return GradedAnswer{}, fmt.Errorf("learning: decode answer payload: %w", err)
		}
	}

	// Grade against the stored choice, never against anything the client sent.
	choice, err := queries.GetChoiceForQuestion(ctx, db.GetChoiceForQuestionParams{
		QuestionID:    *ev.QuestionID,
		InstitutionID: ev.InstitutionID,
		Label:         strings.ToUpper(strings.TrimSpace(payload.ChoiceLabel)),
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return GradedAnswer{}, ErrChoiceNotFound
		}
		return GradedAnswer{}, fmt.Errorf("learning: look up choice: %w", err)
	}

	question, err := queries.GetQuestionMarks(ctx, db.GetQuestionMarksParams{
		ID:            *ev.QuestionID,
		InstitutionID: ev.InstitutionID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return GradedAnswer{}, ErrQuestionNotFound
		}
		return GradedAnswer{}, fmt.Errorf("learning: look up question: %w", err)
	}

	awarded := int32(0)
	if choice.IsCorrect {
		awarded = question.Marks
	}

	progress, err := queries.ApplyAnswerToProgress(ctx, db.ApplyAnswerToProgressParams{
		LearnerID:     ev.LearnerID,
		AssessmentID:  question.AssessmentID,
		InstitutionID: ev.InstitutionID,
	})
	if err != nil {
		return GradedAnswer{}, fmt.Errorf("learning: update assessment progress: %w", err)
	}

	return GradedAnswer{
		QuestionID:   *ev.QuestionID,
		ChoiceLabel:  choice.Label,
		Correct:      choice.IsCorrect,
		Marks:        question.Marks,
		MarksAwarded: awarded,
		MarksTotal:   progress.MarksAvailable,
		Percent:      progress.Percent,
	}, nil
}

// applyLessonProgress moves a lesson's projection row forward.
func (s *Service) applyLessonProgress(ctx context.Context, queries *db.Queries, ev Event) error {
	status := "in_progress"
	if ev.Kind == KindLessonCompleted {
		status = "completed"
	}

	_, err := queries.UpsertLessonProgress(ctx, db.UpsertLessonProgressParams{
		InstitutionID: ev.InstitutionID,
		LearnerID:     ev.LearnerID,
		LessonID:      *ev.LessonID,
		Status:        status,
	})
	if err != nil {
		return fmt.Errorf("learning: update lesson progress: %w", err)
	}
	return nil
}

// enqueueNotification writes the outbox row that the SMS worker will drain in
// milestone 2. It is written here, in the same transaction, so state and
// notification cannot diverge.
func (s *Service) enqueueNotification(ctx context.Context, queries *db.Queries, ev Event) error {
	msisdn, err := queries.GetLearnerMSISDN(ctx, db.GetLearnerMSISDNParams{
		ID:            ev.LearnerID,
		InstitutionID: ev.InstitutionID,
	})
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("learning: resolve learner msisdn: %w", err)
	}

	payload, err := json.Marshal(map[string]any{
		"kind":        string(ev.Kind),
		"source":      string(ev.Source),
		"learner_id":  ev.LearnerID,
		"occurred_at": ev.OccurredAt.UTC().Format(time.RFC3339),
	})
	if err != nil {
		return fmt.Errorf("learning: encode outbox payload: %w", err)
	}

	// A nil msisdn means the learner cannot be reached by SMS: a purely web
	// user, or a phone number that has not been collected yet. The event
	// still belongs in the log; only the notification is skipped.
	var destination *string
	if msisdn != nil && *msisdn != "" {
		destination = msisdn
	}

	_, err = queries.EnqueueOutbox(ctx, db.EnqueueOutboxParams{
		InstitutionID:     ev.InstitutionID,
		EventID:           uuidParam(ev.EventID),
		Topic:             "learning." + string(ev.Kind),
		Payload:           payload,
		DestinationMsisdn: destination,
	})
	if err != nil {
		return fmt.Errorf("learning: enqueue notification: %w", err)
	}
	return nil
}

// validate enforces the invariants the ingest path depends on. It rejects
// events that could not be projected rather than storing something the
// projection cannot represent.
func (ev Event) validate() error {
	if ev.EventID == uuid.Nil {
		return ErrEventIDRequired
	}
	if ev.InstitutionID <= 0 {
		return ErrLearnerRequired
	}
	if ev.LearnerID <= 0 {
		return ErrLearnerRequired
	}
	if ev.Kind == "" {
		return ErrKindRequired
	}
	if !ev.Kind.IsValid() {
		return ErrKindInvalid
	}
	if ev.Source == "" {
		ev.Source = SourceWeb
	}
	if !ev.Source.IsValid() {
		return ErrSourceInvalid
	}

	switch ev.Kind {
	case KindQuestionAnswered:
		if ev.QuestionID == nil {
			return ErrQuestionRequired
		}
		var p AnswerPayload
		if len(ev.Payload) == 0 {
			return ErrChoiceRequired
		}
		if err := json.Unmarshal(ev.Payload, &p); err != nil {
			return ErrChoiceRequired
		}
		if strings.TrimSpace(p.ChoiceLabel) == "" {
			return ErrChoiceRequired
		}
	case KindLessonStarted, KindLessonCompleted:
		if ev.LessonID == nil {
			return ErrLessonRequired
		}
	}

	return nil
}

func uuidParam(id uuid.UUID) pgtype.UUID {
	return pgtype.UUID{Bytes: id, Valid: true}
}
