// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authoring.sql

package db

import (
	"context"
)

const countChoicesForQuestion = `-- name: CountChoicesForQuestion :one
SELECT
    count(*)                          AS total,
    count(*) FILTER (WHERE is_correct) AS correct
FROM choices
WHERE question_id = $1
`

type CountChoicesForQuestionRow struct {
	Total   int64 `json:"total"`
	Correct int64 `json:"correct"`
}

// Used by the seed command to assert the "exactly one correct answer" rule
// that a partial unique index cannot express.
func (q *Queries) CountChoicesForQuestion(ctx context.Context, questionID int64) (CountChoicesForQuestionRow, error) {
	row := q.db.QueryRow(ctx, countChoicesForQuestion, questionID)
	var i CountChoicesForQuestionRow
	err := row.Scan(&i.Total, &i.Correct)
	return i, err
}

const countCourses = `-- name: CountCourses :one
SELECT count(*) FROM courses WHERE institution_id = $1
`

func (q *Queries) CountCourses(ctx context.Context, institutionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, institutionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInstitutions = `-- name: CountInstitutions :one
SELECT count(*) FROM institutions
`

func (q *Queries) CountInstitutions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstitutions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (course_id, institution_id, title, description, published, sms_eligible, position)
VALUES ($1, $2, $3, $5::text,
        $6::boolean, $7::boolean, $4)
RETURNING id, title, published, sms_eligible
`

type CreateAssessmentParams struct {
	CourseID      int64   `json:"course_id"`
	InstitutionID int64   `json:"institution_id"`
	Title         string  `json:"title"`
	Position      int32   `json:"position"`
	Description   *string `json:"description"`
	Published     bool    `json:"published"`
	SmsEligible   bool    `json:"sms_eligible"`
}

type CreateAssessmentRow struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Published   bool   `json:"published"`
	SmsEligible bool   `json:"sms_eligible"`
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (CreateAssessmentRow, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.CourseID,
		arg.InstitutionID,
		arg.Title,
		arg.Position,
		arg.Description,
		arg.Published,
		arg.SmsEligible,
	)
	var i CreateAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Published,
		&i.SmsEligible,
	)
	return i, err
}

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (question_id, institution_id, label, body, is_correct, position)
VALUES ($1, $2, $3, $4, $6::boolean, $5)
RETURNING id, label, body, is_correct, position
`

type CreateChoiceParams struct {
	QuestionID    int64  `json:"question_id"`
	InstitutionID int64  `json:"institution_id"`
	Label         string `json:"label"`
	Body          string `json:"body"`
	Position      int32  `json:"position"`
	IsCorrect     bool   `json:"is_correct"`
}

type CreateChoiceRow struct {
	ID        int64  `json:"id"`
	Label     string `json:"label"`
	Body      string `json:"body"`
	IsCorrect bool   `json:"is_correct"`
	Position  int32  `json:"position"`
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (CreateChoiceRow, error) {
	row := q.db.QueryRow(ctx, createChoice,
		arg.QuestionID,
		arg.InstitutionID,
		arg.Label,
		arg.Body,
		arg.Position,
		arg.IsCorrect,
	)
	var i CreateChoiceRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Body,
		&i.IsCorrect,
		&i.Position,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (institution_id, code, title, description, published)
VALUES ($1, $2, $3, $4::text, $5::boolean)
RETURNING id, code, title, published
`

type CreateCourseParams struct {
	InstitutionID int64   `json:"institution_id"`
	Code          string  `json:"code"`
	Title         string  `json:"title"`
	Description   *string `json:"description"`
	Published     bool    `json:"published"`
}

type CreateCourseRow struct {
	ID        int64  `json:"id"`
	Code      string `json:"code"`
	Title     string `json:"title"`
	Published bool   `json:"published"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.InstitutionID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Published,
	)
	var i CreateCourseRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Published,
	)
	return i, err
}

const createInstitution = `-- name: CreateInstitution :one

INSERT INTO institutions (slug, name)
VALUES ($1, $2)
RETURNING id, slug, name
`

type CreateInstitutionParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type CreateInstitutionRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// Authoring queries.
//
// Not exercised by the API in milestone 1: there is no teacher interface yet.
// They exist so the schema can be exercised end-to-end by the seed command and
// so the next milestone adds endpoints rather than starting from scratch.
func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (CreateInstitutionRow, error) {
	row := q.db.QueryRow(ctx, createInstitution, arg.Slug, arg.Name)
	var i CreateInstitutionRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (module_id, institution_id, title, body_markdown, sms_eligible, position)
VALUES ($1, $2, $3, $5::text, $6::boolean, $4)
RETURNING id, title, sms_eligible, position
`

type CreateLessonParams struct {
	ModuleID      int64   `json:"module_id"`
	InstitutionID int64   `json:"institution_id"`
	Title         string  `json:"title"`
	Position      int32   `json:"position"`
	BodyMarkdown  *string `json:"body_markdown"`
	SmsEligible   bool    `json:"sms_eligible"`
}

type CreateLessonRow struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	SmsEligible bool   `json:"sms_eligible"`
	Position    int32  `json:"position"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (CreateLessonRow, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ModuleID,
		arg.InstitutionID,
		arg.Title,
		arg.Position,
		arg.BodyMarkdown,
		arg.SmsEligible,
	)
	var i CreateLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SmsEligible,
		&i.Position,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one
INSERT INTO modules (course_id, institution_id, title, position)
VALUES ($1, $2, $3, $4)
RETURNING id, title, position
`

type CreateModuleParams struct {
	CourseID      int64  `json:"course_id"`
	InstitutionID int64  `json:"institution_id"`
	Title         string `json:"title"`
	Position      int32  `json:"position"`
}

type CreateModuleRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (CreateModuleRow, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.CourseID,
		arg.InstitutionID,
		arg.Title,
		arg.Position,
	)
	var i CreateModuleRow
	err := row.Scan(&i.ID, &i.Title, &i.Position)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (assessment_id, institution_id, kind, prompt, marks, position)
VALUES ($1, $2, $5::question_kind, $3, $6::int, $4)
RETURNING id, prompt, marks, position
`

type CreateQuestionParams struct {
	AssessmentID  int64        `json:"assessment_id"`
	InstitutionID int64        `json:"institution_id"`
	Prompt        string       `json:"prompt"`
	Position      int32        `json:"position"`
	Kind          QuestionKind `json:"kind"`
	Marks         int32        `json:"marks"`
}

type CreateQuestionRow struct {
	ID       int64  `json:"id"`
	Prompt   string `json:"prompt"`
	Marks    int32  `json:"marks"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (CreateQuestionRow, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.AssessmentID,
		arg.InstitutionID,
		arg.Prompt,
		arg.Position,
		arg.Kind,
		arg.Marks,
	)
	var i CreateQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Marks,
		&i.Position,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (institution_id, email, display_name, role, password_hash, msisdn)
VALUES ($1, $2, $3, $4, $5::text, $6::text)
RETURNING id, institution_id, email, display_name, role, msisdn
`

type CreateUserParams struct {
	InstitutionID int64    `json:"institution_id"`
	Email         string   `json:"email"`
	DisplayName   string   `json:"display_name"`
	Role          UserRole `json:"role"`
	PasswordHash  *string  `json:"password_hash"`
	Msisdn        *string  `json:"msisdn"`
}

type CreateUserRow struct {
	ID            int64    `json:"id"`
	InstitutionID int64    `json:"institution_id"`
	Email         string   `json:"email"`
	DisplayName   string   `json:"display_name"`
	Role          UserRole `json:"role"`
	Msisdn        *string  `json:"msisdn"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.InstitutionID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
		arg.Msisdn,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Msisdn,
	)
	return i, err
}

const enrolLearner = `-- name: EnrolLearner :one
INSERT INTO course_enrollments (course_id, learner_id, institution_id, assigned_by)
VALUES ($1, $2, $3, $4::bigint)
ON CONFLICT (course_id, learner_id) DO NOTHING
RETURNING id
`

type EnrolLearnerParams struct {
	CourseID      int64  `json:"course_id"`
	LearnerID     int64  `json:"learner_id"`
	InstitutionID int64  `json:"institution_id"`
	AssignedBy    *int64 `json:"assigned_by"`
}

func (q *Queries) EnrolLearner(ctx context.Context, arg EnrolLearnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, enrolLearner,
		arg.CourseID,
		arg.LearnerID,
		arg.InstitutionID,
		arg.AssignedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
