// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssessmentProgress = `-- name: GetAssessmentProgress :one
SELECT
    status,
    questions_answered,
    questions_correct,
    marks_awarded,
    marks_available,
    percent,
    started_at,
    completed_at
FROM progress
WHERE learner_id = $1
  AND assessment_id = $2
  AND institution_id = $3
`

type GetAssessmentProgressParams struct {
	LearnerID     int64  `json:"learner_id"`
	AssessmentID  *int64 `json:"assessment_id"`
	InstitutionID int64  `json:"institution_id"`
}

type GetAssessmentProgressRow struct {
	Status            string             `json:"status"`
	QuestionsAnswered int32              `json:"questions_answered"`
	QuestionsCorrect  int32              `json:"questions_correct"`
	MarksAwarded      int32              `json:"marks_awarded"`
	MarksAvailable    int32              `json:"marks_available"`
	Percent           int32              `json:"percent"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetAssessmentProgress(ctx context.Context, arg GetAssessmentProgressParams) (GetAssessmentProgressRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentProgress, arg.LearnerID, arg.AssessmentID, arg.InstitutionID)
	var i GetAssessmentProgressRow
	err := row.Scan(
		&i.Status,
		&i.QuestionsAnswered,
		&i.QuestionsCorrect,
		&i.MarksAwarded,
		&i.MarksAvailable,
		&i.Percent,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAssessmentWithQuestions = `-- name: GetAssessmentWithQuestions :many
SELECT
    a.id            AS assessment_id,
    a.title         AS assessment_title,
    a.description   AS assessment_description,
    a.sms_eligible  AS sms_eligible,
    q.id            AS question_id,
    q.kind          AS question_kind,
    q.prompt        AS prompt,
    q.marks         AS marks,
    q.position      AS question_position
FROM assessments a
LEFT JOIN questions q ON q.assessment_id = a.id
WHERE a.id = $1
  AND a.institution_id = $2
ORDER BY q.position
`

type GetAssessmentWithQuestionsParams struct {
	AssessmentID  int64 `json:"assessment_id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetAssessmentWithQuestionsRow struct {
	AssessmentID          int64         `json:"assessment_id"`
	AssessmentTitle       string        `json:"assessment_title"`
	AssessmentDescription string        `json:"assessment_description"`
	SmsEligible           bool          `json:"sms_eligible"`
	QuestionID            *int64        `json:"question_id"`
	QuestionKind          *QuestionKind `json:"question_kind"`
	Prompt                *string       `json:"prompt"`
	Marks                 *int32        `json:"marks"`
	QuestionPosition      *int32        `json:"question_position"`
}

func (q *Queries) GetAssessmentWithQuestions(ctx context.Context, arg GetAssessmentWithQuestionsParams) ([]GetAssessmentWithQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getAssessmentWithQuestions, arg.AssessmentID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssessmentWithQuestionsRow{}
	for rows.Next() {
		var i GetAssessmentWithQuestionsRow
		if err := rows.Scan(
			&i.AssessmentID,
			&i.AssessmentTitle,
			&i.AssessmentDescription,
			&i.SmsEligible,
			&i.QuestionID,
			&i.QuestionKind,
			&i.Prompt,
			&i.Marks,
			&i.QuestionPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT
    c.id,
    c.code,
    c.title,
    c.description,
    c.published
FROM courses c
WHERE c.id = $1
  AND c.institution_id = $2
`

type GetCourseParams struct {
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetCourseRow struct {
	ID          int64  `json:"id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Published   bool   `json:"published"`
}

func (q *Queries) GetCourse(ctx context.Context, arg GetCourseParams) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, arg.CourseID, arg.InstitutionID)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Published,
	)
	return i, err
}

const getLearnerAnswer = `-- name: GetLearnerAnswer :one
SELECT
    payload ->> 'choice_label' AS choice_label,
    received_at
FROM learning_events
WHERE learner_id = $1
  AND question_id = $2
  AND institution_id = $3
  AND kind = 'question_answered'
ORDER BY received_at DESC
LIMIT 1
`

type GetLearnerAnswerParams struct {
	LearnerID     int64  `json:"learner_id"`
	QuestionID    *int64 `json:"question_id"`
	InstitutionID int64  `json:"institution_id"`
}

type GetLearnerAnswerRow struct {
	ChoiceLabel interface{} `json:"choice_label"`
	ReceivedAt  time.Time   `json:"received_at"`
}

// Which label the learner submitted for a question, used to render a
// previously-answered state.
func (q *Queries) GetLearnerAnswer(ctx context.Context, arg GetLearnerAnswerParams) (GetLearnerAnswerRow, error) {
	row := q.db.QueryRow(ctx, getLearnerAnswer, arg.LearnerID, arg.QuestionID, arg.InstitutionID)
	var i GetLearnerAnswerRow
	err := row.Scan(&i.ChoiceLabel, &i.ReceivedAt)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT
    l.id,
    l.module_id,
    l.title,
    l.body_markdown,
    l.sms_eligible,
    l.position,
    m.course_id
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE l.id = $1
  AND l.institution_id = $2
`

type GetLessonParams struct {
	LessonID      int64 `json:"lesson_id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetLessonRow struct {
	ID           int64  `json:"id"`
	ModuleID     int64  `json:"module_id"`
	Title        string `json:"title"`
	BodyMarkdown string `json:"body_markdown"`
	SmsEligible  bool   `json:"sms_eligible"`
	Position     int32  `json:"position"`
	CourseID     int64  `json:"course_id"`
}

func (q *Queries) GetLesson(ctx context.Context, arg GetLessonParams) (GetLessonRow, error) {
	row := q.db.QueryRow(ctx, getLesson, arg.LessonID, arg.InstitutionID)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.BodyMarkdown,
		&i.SmsEligible,
		&i.Position,
		&i.CourseID,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT
    status,
    questions_answered,
    questions_correct,
    marks_awarded,
    marks_available,
    percent,
    started_at,
    completed_at
FROM progress
WHERE learner_id = $1
  AND lesson_id = $2
  AND institution_id = $3
`

type GetLessonProgressParams struct {
	LearnerID     int64  `json:"learner_id"`
	LessonID      *int64 `json:"lesson_id"`
	InstitutionID int64  `json:"institution_id"`
}

type GetLessonProgressRow struct {
	Status            string             `json:"status"`
	QuestionsAnswered int32              `json:"questions_answered"`
	QuestionsCorrect  int32              `json:"questions_correct"`
	MarksAwarded      int32              `json:"marks_awarded"`
	MarksAvailable    int32              `json:"marks_available"`
	Percent           int32              `json:"percent"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (GetLessonProgressRow, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.LearnerID, arg.LessonID, arg.InstitutionID)
	var i GetLessonProgressRow
	err := row.Scan(
		&i.Status,
		&i.QuestionsAnswered,
		&i.QuestionsCorrect,
		&i.MarksAwarded,
		&i.MarksAvailable,
		&i.Percent,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAssessmentsForCourse = `-- name: ListAssessmentsForCourse :many
SELECT
    a.id,
    a.title,
    a.description,
    a.position,
    a.sms_eligible,
    COALESCE(p.status, 'not_started') AS progress_status,
    COALESCE(p.percent, 0)           AS percent,
    COALESCE(p.marks_awarded, 0)     AS marks_awarded,
    COALESCE(p.marks_available, 0)   AS marks_available
FROM assessments a
LEFT JOIN progress p
  ON p.assessment_id = a.id
 AND p.learner_id = $1
WHERE a.course_id = $2
  AND a.institution_id = $3
  AND a.published = true
ORDER BY a.position
`

type ListAssessmentsForCourseParams struct {
	LearnerID     int64 `json:"learner_id"`
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListAssessmentsForCourseRow struct {
	ID             int64  `json:"id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Position       int32  `json:"position"`
	SmsEligible    bool   `json:"sms_eligible"`
	ProgressStatus string `json:"progress_status"`
	Percent        int32  `json:"percent"`
	MarksAwarded   int32  `json:"marks_awarded"`
	MarksAvailable int32  `json:"marks_available"`
}

func (q *Queries) ListAssessmentsForCourse(ctx context.Context, arg ListAssessmentsForCourseParams) ([]ListAssessmentsForCourseRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentsForCourse, arg.LearnerID, arg.CourseID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssessmentsForCourseRow{}
	for rows.Next() {
		var i ListAssessmentsForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.SmsEligible,
			&i.ProgressStatus,
			&i.Percent,
			&i.MarksAwarded,
			&i.MarksAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesForAssessment = `-- name: ListChoicesForAssessment :many
SELECT
    ch.id,
    ch.question_id,
    ch.label,
    ch.body,
    ch.is_correct,
    ch.position
FROM choices ch
JOIN questions q ON q.id = ch.question_id
WHERE q.assessment_id = $1
  AND ch.institution_id = $2
ORDER BY ch.question_id, ch.position
`

type ListChoicesForAssessmentParams struct {
	AssessmentID  int64 `json:"assessment_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListChoicesForAssessmentRow struct {
	ID         int64  `json:"id"`
	QuestionID int64  `json:"question_id"`
	Label      string `json:"label"`
	Body       string `json:"body"`
	IsCorrect  bool   `json:"is_correct"`
	Position   int32  `json:"position"`
}

// is_correct is projected but the HTTP layer must never send it to a learner
// before submission. See httpapi.writeProgress.
func (q *Queries) ListChoicesForAssessment(ctx context.Context, arg ListChoicesForAssessmentParams) ([]ListChoicesForAssessmentRow, error) {
	rows, err := q.db.Query(ctx, listChoicesForAssessment, arg.AssessmentID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChoicesForAssessmentRow{}
	for rows.Next() {
		var i ListChoicesForAssessmentRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.Body,
			&i.IsCorrect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolledCourses = `-- name: ListEnrolledCourses :many
SELECT
    c.id,
    c.code,
    c.title,
    c.description
FROM courses c
JOIN course_enrollments ce
  ON ce.course_id = c.id
 AND ce.learner_id = $1
WHERE c.institution_id = $2
  AND c.published = true
ORDER BY c.title
`

type ListEnrolledCoursesParams struct {
	LearnerID     int64 `json:"learner_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListEnrolledCoursesRow struct {
	ID          int64  `json:"id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) ListEnrolledCourses(ctx context.Context, arg ListEnrolledCoursesParams) ([]ListEnrolledCoursesRow, error) {
	rows, err := q.db.Query(ctx, listEnrolledCourses, arg.LearnerID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrolledCoursesRow{}
	for rows.Next() {
		var i ListEnrolledCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesWithLessons = `-- name: ListModulesWithLessons :many
SELECT
    m.id                AS module_id,
    m.title             AS module_title,
    m.position          AS module_position,
    l.id                AS lesson_id,
    l.title             AS lesson_title,
    l.sms_eligible      AS sms_eligible,
    l.position          AS lesson_position,
    COALESCE(p.status, 'not_started') AS progress_status,
    COALESCE(p.percent, 0)           AS percent
FROM modules m
LEFT JOIN lessons l
  ON l.module_id = m.id
LEFT JOIN progress p
  ON p.lesson_id = l.id
 AND p.learner_id = $1
WHERE m.course_id = $2
  AND m.institution_id = $3
ORDER BY m.position, l.position
`

type ListModulesWithLessonsParams struct {
	LearnerID     int64 `json:"learner_id"`
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListModulesWithLessonsRow struct {
	ModuleID       int64   `json:"module_id"`
	ModuleTitle    string  `json:"module_title"`
	ModulePosition int32   `json:"module_position"`
	LessonID       *int64  `json:"lesson_id"`
	LessonTitle    *string `json:"lesson_title"`
	SmsEligible    *bool   `json:"sms_eligible"`
	LessonPosition *int32  `json:"lesson_position"`
	ProgressStatus string  `json:"progress_status"`
	Percent        int32   `json:"percent"`
}

// Returns one flat, ordered list; the service groups it in memory. A flat
// query avoids the row-multiplication a nested rows.Cursor would produce
// across the modules/lessons cross product.
func (q *Queries) ListModulesWithLessons(ctx context.Context, arg ListModulesWithLessonsParams) ([]ListModulesWithLessonsRow, error) {
	rows, err := q.db.Query(ctx, listModulesWithLessons, arg.LearnerID, arg.CourseID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModulesWithLessonsRow{}
	for rows.Next() {
		var i ListModulesWithLessonsRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.ModuleTitle,
			&i.ModulePosition,
			&i.LessonID,
			&i.LessonTitle,
			&i.SmsEligible,
			&i.LessonPosition,
			&i.ProgressStatus,
			&i.Percent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
