// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyAnswerToProgress = `-- name: ApplyAnswerToProgress :one
INSERT INTO progress (
    institution_id,
    learner_id,
    course_id,
    assessment_id,
    entity,
    status,
    marks_awarded,
    marks_available,
    questions_answered,
    questions_correct
)
SELECT
    a.institution_id,
    $1,
    a.course_id,
    a.id,
    'assessment',
    'in_progress',
    COALESCE(scored.marks_awarded, 0),
    (SELECT COALESCE(SUM(q.marks), 0) FROM questions q WHERE q.assessment_id = a.id),
    COALESCE(scored.answered, 0),
    COALESCE(scored.correct, 0)
FROM assessments a
LEFT JOIN LATERAL (
    -- Recomputed from the log on every ingest, rather than incremented.
    --
    -- DISTINCT ON collapses a re-answered question to a single answer.
    -- Without it, answering the same question correctly twice would count two
    -- marks for one question.
    --
    -- Ordered by occurred_at, not received_at. This matters: an offline queue
    -- can replay events in the wrong order, so a stale answer may arrive last.
    -- Ranking by arrival would let the stale answer overwrite the newer one.
    -- occurred_at is the learner's clock and reflects intent; received_at only
    -- reflects when the network delivered it. id DESC breaks ties for
    -- same-microsecond events.
    --
    -- correctness comes from the choice matching the label actually picked,
    -- never from the question row.
    SELECT
        COUNT(*) FILTER (WHERE ch.is_correct)                   AS correct,
        COUNT(*)                                                AS answered,
        COALESCE(SUM(q.marks) FILTER (WHERE ch.is_correct), 0)  AS marks_awarded
    FROM (
        SELECT DISTINCT ON (ev.question_id)
            ev.question_id,
            ev.payload ->> 'choice_label' AS label
        FROM learning_events ev
        WHERE ev.learner_id = $1
          AND ev.kind = 'question_answered'
          AND ev.question_id IN (SELECT id FROM questions WHERE assessment_id = a.id)
        ORDER BY ev.question_id, ev.occurred_at DESC, ev.id DESC
    ) latest
    JOIN questions q ON q.id = latest.question_id
    JOIN choices ch
      ON ch.question_id = latest.question_id
     AND ch.label = latest.label
) scored ON true
WHERE a.id = $2
  AND a.institution_id = $3
  AND EXISTS (
      SELECT 1
      FROM course_enrollments ce
      WHERE ce.course_id = a.course_id
        AND ce.learner_id = $1
  )
ON CONFLICT (learner_id, entity, COALESCE(lesson_id, 0), COALESCE(assessment_id, 0))
DO UPDATE SET
    status = 'in_progress',
    marks_awarded = EXCLUDED.marks_awarded,
    marks_available = EXCLUDED.marks_available,
    questions_answered = EXCLUDED.questions_answered,
    questions_correct = EXCLUDED.questions_correct,
    percent = CASE
        WHEN EXCLUDED.marks_available = 0 THEN 0
        ELSE LEAST(100, (EXCLUDED.marks_awarded * 100) / EXCLUDED.marks_available)
    END,
    started_at = COALESCE(progress.started_at, now()),
    updated_at = now()
RETURNING
    id,
    status,
    questions_answered,
    questions_correct,
    marks_awarded,
    marks_available,
    percent
`

type ApplyAnswerToProgressParams struct {
	LearnerID     int64 `json:"learner_id"`
	AssessmentID  int64 `json:"assessment_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ApplyAnswerToProgressRow struct {
	ID                int64  `json:"id"`
	Status            string `json:"status"`
	QuestionsAnswered int32  `json:"questions_answered"`
	QuestionsCorrect  int32  `json:"questions_correct"`
	MarksAwarded      int32  `json:"marks_awarded"`
	MarksAvailable    int32  `json:"marks_available"`
	Percent           int32  `json:"percent"`
}

// Applies one graded answer to an assessment's running totals.
//
// Guarded against double counting: the caller only reaches this query when
// InsertLearningEvent actually inserted a row, so a replayed event never gets
// here twice.
//
// The correct count is recomputed from distinct answered questions rather than
// incremented, which keeps the projection consistent even if a learner
// re-answers the same question through a second device.
func (q *Queries) ApplyAnswerToProgress(ctx context.Context, arg ApplyAnswerToProgressParams) (ApplyAnswerToProgressRow, error) {
	row := q.db.QueryRow(ctx, applyAnswerToProgress, arg.LearnerID, arg.AssessmentID, arg.InstitutionID)
	var i ApplyAnswerToProgressRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.QuestionsAnswered,
		&i.QuestionsCorrect,
		&i.MarksAwarded,
		&i.MarksAvailable,
		&i.Percent,
	)
	return i, err
}

const enqueueOutbox = `-- name: EnqueueOutbox :one
INSERT INTO outbox (institution_id, event_id, topic, payload, destination_msisdn)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type EnqueueOutboxParams struct {
	InstitutionID     int64       `json:"institution_id"`
	EventID           pgtype.UUID `json:"event_id"`
	Topic             string      `json:"topic"`
	Payload           []byte      `json:"payload"`
	DestinationMsisdn *string     `json:"destination_msisdn"`
}

// Written in the same transaction as the event, so state and notification
// cannot diverge. Nothing reads this table until milestone 2.
func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueOutbox,
		arg.InstitutionID,
		arg.EventID,
		arg.Topic,
		arg.Payload,
		arg.DestinationMsisdn,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getChoiceForQuestion = `-- name: GetChoiceForQuestion :one
SELECT
    id,
    question_id,
    label,
    body,
    is_correct
FROM choices
WHERE question_id = $1
  AND institution_id = $2
  AND label = $3
`

type GetChoiceForQuestionParams struct {
	QuestionID    int64  `json:"question_id"`
	InstitutionID int64  `json:"institution_id"`
	Label         string `json:"label"`
}

type GetChoiceForQuestionRow struct {
	ID         int64  `json:"id"`
	QuestionID int64  `json:"question_id"`
	Label      string `json:"label"`
	Body       string `json:"body"`
	IsCorrect  bool   `json:"is_correct"`
}

// Returns the choice matching a label, used to grade a submitted answer.
func (q *Queries) GetChoiceForQuestion(ctx context.Context, arg GetChoiceForQuestionParams) (GetChoiceForQuestionRow, error) {
	row := q.db.QueryRow(ctx, getChoiceForQuestion, arg.QuestionID, arg.InstitutionID, arg.Label)
	var i GetChoiceForQuestionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Body,
		&i.IsCorrect,
	)
	return i, err
}

const getCourseProgress = `-- name: GetCourseProgress :many
SELECT
    c.id           AS course_id,
    c.code,
    c.title,
    COALESCE(lesson_counts.total, 0)::bigint       AS lessons_total,
    COALESCE(lesson_counts.completed, 0)::bigint   AS lessons_completed,
    COALESCE(mark_counts.awarded, 0)::int         AS marks_awarded,
    COALESCE(mark_counts.available, 0)::int       AS marks_available
FROM courses c
JOIN course_enrollments ce
  ON ce.course_id = c.id
 AND ce.learner_id = $1
LEFT JOIN LATERAL (
    SELECT
        COUNT(l.id) FILTER (WHERE p.status = 'completed') AS completed,
        COUNT(l.id)                                        AS total
    FROM modules m
    JOIN lessons l ON l.module_id = m.id
    LEFT JOIN progress p
      ON p.lesson_id = l.id
     AND p.learner_id = $1
    WHERE m.course_id = c.id
) lesson_counts ON true
LEFT JOIN LATERAL (
    -- SUM over INT columns yields BIGINT while the 0 fallback is INTEGER, so
    -- both branches are cast to INT. Without this the result type is
    -- untyped "any" and codegen gives up, producing interface{}.
    SELECT
        COALESCE(SUM(p.marks_awarded)::int, 0)   AS awarded,
        COALESCE(SUM(p.marks_available)::int, 0) AS available
    FROM progress p
    WHERE p.course_id = c.id
      AND p.learner_id = $1
      AND p.entity = 'assessment'
) mark_counts ON true
WHERE c.institution_id = $2
  AND c.published = true
ORDER BY c.title
`

type GetCourseProgressParams struct {
	LearnerID     int64 `json:"learner_id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetCourseProgressRow struct {
	CourseID         int64  `json:"course_id"`
	Code             string `json:"code"`
	Title            string `json:"title"`
	LessonsTotal     int64  `json:"lessons_total"`
	LessonsCompleted int64  `json:"lessons_completed"`
	MarksAwarded     int32  `json:"marks_awarded"`
	MarksAvailable   int32  `json:"marks_available"`
}

// Lesson totals and mark totals are computed in independent LATERAL
// subqueries on purpose.
//
// Joining lessons and assessment-progress rows into one FROM clause multiplies
// rows: with three lessons and three assessments, each lesson row would carry
// the assessment totals three times and the SUM would triple. Subqueries keep
// each total independent.
func (q *Queries) GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) ([]GetCourseProgressRow, error) {
	rows, err := q.db.Query(ctx, getCourseProgress, arg.LearnerID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCourseProgressRow{}
	for rows.Next() {
		var i GetCourseProgressRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Code,
			&i.Title,
			&i.LessonsTotal,
			&i.LessonsCompleted,
			&i.MarksAwarded,
			&i.MarksAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnerMSISDN = `-- name: GetLearnerMSISDN :one
SELECT msisdn
FROM users
WHERE id = $1
  AND institution_id = $2
  AND msisdn IS NOT NULL
`

type GetLearnerMSISDNParams struct {
	ID            int64 `json:"id"`
	InstitutionID int64 `json:"institution_id"`
}

func (q *Queries) GetLearnerMSISDN(ctx context.Context, arg GetLearnerMSISDNParams) (*string, error) {
	row := q.db.QueryRow(ctx, getLearnerMSISDN, arg.ID, arg.InstitutionID)
	var msisdn *string
	err := row.Scan(&msisdn)
	return msisdn, err
}

const getQuestionMarks = `-- name: GetQuestionMarks :one
SELECT
    q.id,
    q.assessment_id,
    q.marks,
    a.course_id,
    a.institution_id
FROM questions q
JOIN assessments a ON a.id = q.assessment_id
WHERE q.id = $1
  AND q.institution_id = $2
`

type GetQuestionMarksParams struct {
	ID            int64 `json:"id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetQuestionMarksRow struct {
	ID            int64 `json:"id"`
	AssessmentID  int64 `json:"assessment_id"`
	Marks         int32 `json:"marks"`
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
}

func (q *Queries) GetQuestionMarks(ctx context.Context, arg GetQuestionMarksParams) (GetQuestionMarksRow, error) {
	row := q.db.QueryRow(ctx, getQuestionMarks, arg.ID, arg.InstitutionID)
	var i GetQuestionMarksRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Marks,
		&i.CourseID,
		&i.InstitutionID,
	)
	return i, err
}

const insertLearningEvent = `-- name: InsertLearningEvent :one

INSERT INTO learning_events (
    event_id,
    institution_id,
    learner_id,
    course_id,
    lesson_id,
    assessment_id,
    question_id,
    kind,
    source,
    payload,
    occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, received_at
`

type InsertLearningEventParams struct {
	EventID       pgtype.UUID `json:"event_id"`
	InstitutionID int64       `json:"institution_id"`
	LearnerID     int64       `json:"learner_id"`
	CourseID      *int64      `json:"course_id"`
	LessonID      *int64      `json:"lesson_id"`
	AssessmentID  *int64      `json:"assessment_id"`
	QuestionID    *int64      `json:"question_id"`
	Kind          EventKind   `json:"kind"`
	Source        EventSource `json:"source"`
	Payload       []byte      `json:"payload"`
	OccurredAt    time.Time   `json:"occurred_at"`
}

type InsertLearningEventRow struct {
	ID         int64       `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	ReceivedAt time.Time   `json:"received_at"`
}

// Learning event ingest and progress projection.
//
// The idempotency guarantee lives in InsertLearningEvent's ON CONFLICT
// DO NOTHING. InsertEvent returns the row only when it was actually written,
// so the caller can skip projection work for a duplicate -- which is what
// makes a learner who texts the same answer twice score it once.
func (q *Queries) InsertLearningEvent(ctx context.Context, arg InsertLearningEventParams) (InsertLearningEventRow, error) {
	row := q.db.QueryRow(ctx, insertLearningEvent,
		arg.EventID,
		arg.InstitutionID,
		arg.LearnerID,
		arg.CourseID,
		arg.LessonID,
		arg.AssessmentID,
		arg.QuestionID,
		arg.Kind,
		arg.Source,
		arg.Payload,
		arg.OccurredAt,
	)
	var i InsertLearningEventRow
	err := row.Scan(&i.ID, &i.EventID, &i.ReceivedAt)
	return i, err
}

const isEnrolled = `-- name: IsEnrolled :one
SELECT EXISTS (
    SELECT 1
    FROM course_enrollments
    WHERE course_id = $1
      AND learner_id = $2
)
`

type IsEnrolledParams struct {
	CourseID  int64 `json:"course_id"`
	LearnerID int64 `json:"learner_id"`
}

func (q *Queries) IsEnrolled(ctx context.Context, arg IsEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEnrolled, arg.CourseID, arg.LearnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO progress (
    institution_id,
    learner_id,
    course_id,
    lesson_id,
    entity,
    status,
    started_at,
    completed_at
)
SELECT
    l.institution_id,
    $1,
    m.course_id,
    l.id,
    'lesson',
    $2,
    CASE WHEN $2 = 'in_progress' THEN now() ELSE NULL END,
    CASE WHEN $2 = 'completed' THEN now() ELSE NULL END
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE l.id = $3
  AND l.institution_id = $4
  AND EXISTS (
      -- The learner must be enrolled in the course the lesson belongs to.
      SELECT 1
      FROM course_enrollments ce
      WHERE ce.course_id = m.course_id
        AND ce.learner_id = $1
  )
ON CONFLICT (learner_id, entity, COALESCE(lesson_id, 0), COALESCE(assessment_id, 0))
DO UPDATE SET
    status = CASE
        WHEN progress.status = 'completed' THEN 'completed'
        ELSE EXCLUDED.status
    END,
    -- Completion is sticky: once a lesson is done, a later stale event must
    -- not move it back to in_progress. Out-of-order offline replays make
    -- this a real case, not a theoretical one.
    completed_at = COALESCE(progress.completed_at, EXCLUDED.completed_at),
    started_at = COALESCE(progress.started_at, EXCLUDED.started_at),
    updated_at = now()
RETURNING
    id,
    status,
    questions_answered,
    questions_correct,
    marks_awarded,
    marks_available,
    percent,
    started_at,
    completed_at
`

type UpsertLessonProgressParams struct {
	LearnerID     int64  `json:"learner_id"`
	Status        string `json:"status"`
	LessonID      int64  `json:"lesson_id"`
	InstitutionID int64  `json:"institution_id"`
}

type UpsertLessonProgressRow struct {
	ID                int64              `json:"id"`
	Status            string             `json:"status"`
	QuestionsAnswered int32              `json:"questions_answered"`
	QuestionsCorrect  int32              `json:"questions_correct"`
	MarksAwarded      int32              `json:"marks_awarded"`
	MarksAvailable    int32              `json:"marks_available"`
	Percent           int32              `json:"percent"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

// Ensures a progress row exists and returns it.
//
// institution_id and course_id are derived from the lesson rather than
// supplied by the caller: a client must not be able to record progress
// against a course it does not own, and the learner should not have to know
// the course id to complete a lesson.
func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (UpsertLessonProgressRow, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.LearnerID,
		arg.Status,
		arg.LessonID,
		arg.InstitutionID,
	)
	var i UpsertLessonProgressRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.QuestionsAnswered,
		&i.QuestionsCorrect,
		&i.MarksAwarded,
		&i.MarksAvailable,
		&i.Percent,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
