// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventKind string

const (
	EventKindLessonStarted       EventKind = "lesson_started"
	EventKindLessonCompleted     EventKind = "lesson_completed"
	EventKindQuestionAnswered    EventKind = "question_answered"
	EventKindAssessmentSubmitted EventKind = "assessment_submitted"
)

func (e *EventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventKind(s)
	case string:
		*e = EventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EventKind: %T", src)
	}
	return nil
}

type NullEventKind struct {
	EventKind EventKind `json:"event_kind"`
	Valid     bool      `json:"valid"` // Valid is true if EventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.EventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventKind), nil
}

type EventSource string

const (
	EventSourceWeb EventSource = "web"
	EventSourceSms EventSource = "sms"
	EventSourceStk EventSource = "stk"
)

func (e *EventSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventSource(s)
	case string:
		*e = EventSource(s)
	default:
		return fmt.Errorf("unsupported scan type for EventSource: %T", src)
	}
	return nil
}

type NullEventSource struct {
	EventSource EventSource `json:"event_source"`
	Valid       bool        `json:"valid"` // Valid is true if EventSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventSource) Scan(value interface{}) error {
	if value == nil {
		ns.EventSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventSource), nil
}

type QuestionKind string

const (
	QuestionKindSingleChoice QuestionKind = "single_choice"
)

func (e *QuestionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionKind(s)
	case string:
		*e = QuestionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionKind: %T", src)
	}
	return nil
}

type NullQuestionKind struct {
	QuestionKind QuestionKind `json:"question_kind"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionKind) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionKind), nil
}

type SmsConversationState string

const (
	SmsConversationStateIdle           SmsConversationState = "idle"
	SmsConversationStateAwaitingAnswer SmsConversationState = "awaiting_answer"
	SmsConversationStateAwaitingStart  SmsConversationState = "awaiting_start"
	SmsConversationStateCompleted      SmsConversationState = "completed"
)

func (e *SmsConversationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SmsConversationState(s)
	case string:
		*e = SmsConversationState(s)
	default:
		return fmt.Errorf("unsupported scan type for SmsConversationState: %T", src)
	}
	return nil
}

type NullSmsConversationState struct {
	SmsConversationState SmsConversationState `json:"sms_conversation_state"`
	Valid                bool                 `json:"valid"` // Valid is true if SmsConversationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSmsConversationState) Scan(value interface{}) error {
	if value == nil {
		ns.SmsConversationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SmsConversationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSmsConversationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SmsConversationState), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleTeacher UserRole = "teacher"
	UserRoleStudent UserRole = "student"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Assessment struct {
	ID            int64     `json:"id"`
	CourseID      int64     `json:"course_id"`
	InstitutionID int64     `json:"institution_id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Published     bool      `json:"published"`
	SmsEligible   bool      `json:"sms_eligible"`
	Position      int32     `json:"position"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Exactly one choice per question must have is_correct = true; enforced by the authoring service.
type Choice struct {
	ID            int64  `json:"id"`
	QuestionID    int64  `json:"question_id"`
	InstitutionID int64  `json:"institution_id"`
	Label         string `json:"label"`
	Body          string `json:"body"`
	IsCorrect     bool   `json:"is_correct"`
	Position      int32  `json:"position"`
}

type Course struct {
	ID            int64     `json:"id"`
	InstitutionID int64     `json:"institution_id"`
	Code          string    `json:"code"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Published     bool      `json:"published"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CourseEnrollment struct {
	ID            int64     `json:"id"`
	CourseID      int64     `json:"course_id"`
	LearnerID     int64     `json:"learner_id"`
	InstitutionID int64     `json:"institution_id"`
	AssignedBy    *int64    `json:"assigned_by"`
	CreatedAt     time.Time `json:"created_at"`
}

type Institution struct {
	ID        int64     `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type LearningEvent struct {
	ID            int64       `json:"id"`
	EventID       pgtype.UUID `json:"event_id"`
	InstitutionID int64       `json:"institution_id"`
	LearnerID     int64       `json:"learner_id"`
	CourseID      *int64      `json:"course_id"`
	LessonID      *int64      `json:"lesson_id"`
	AssessmentID  *int64      `json:"assessment_id"`
	QuestionID    *int64      `json:"question_id"`
	Kind          EventKind   `json:"kind"`
	Source        EventSource `json:"source"`
	Payload       []byte      `json:"payload"`
	OccurredAt    time.Time   `json:"occurred_at"`
	ReceivedAt    time.Time   `json:"received_at"`
}

type Lesson struct {
	ID            int64  `json:"id"`
	ModuleID      int64  `json:"module_id"`
	InstitutionID int64  `json:"institution_id"`
	Title         string `json:"title"`
	BodyMarkdown  string `json:"body_markdown"`
	SmsEligible   bool   `json:"sms_eligible"`
	Position      int32  `json:"position"`
}

type Module struct {
	ID            int64  `json:"id"`
	CourseID      int64  `json:"course_id"`
	InstitutionID int64  `json:"institution_id"`
	Title         string `json:"title"`
	Position      int32  `json:"position"`
}

type Outbox struct {
	ID                int64              `json:"id"`
	InstitutionID     int64              `json:"institution_id"`
	EventID           pgtype.UUID        `json:"event_id"`
	Topic             string             `json:"topic"`
	Payload           []byte             `json:"payload"`
	DestinationMsisdn *string            `json:"destination_msisdn"`
	CreatedAt         time.Time          `json:"created_at"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	// Number of delivery attempts. At or above the give-up threshold the row stops being retried and dead_at is set.
	Attempts          int32              `json:"attempts"`
	LastError         *string            `json:"last_error"`
	NextAttemptAt     time.Time          `json:"next_attempt_at"`
	DeadAt            pgtype.Timestamptz `json:"dead_at"`
	ProviderMessageID *string            `json:"provider_message_id"`
}

type Progress struct {
	ID                int64              `json:"id"`
	InstitutionID     int64              `json:"institution_id"`
	LearnerID         int64              `json:"learner_id"`
	CourseID          int64              `json:"course_id"`
	LessonID          *int64             `json:"lesson_id"`
	AssessmentID      *int64             `json:"assessment_id"`
	Entity            string             `json:"entity"`
	Status            string             `json:"status"`
	QuestionsAnswered int32              `json:"questions_answered"`
	QuestionsCorrect  int32              `json:"questions_correct"`
	MarksAwarded      int32              `json:"marks_awarded"`
	MarksAvailable    int32              `json:"marks_available"`
	Percent           int32              `json:"percent"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type Question struct {
	ID            int64        `json:"id"`
	AssessmentID  int64        `json:"assessment_id"`
	InstitutionID int64        `json:"institution_id"`
	Kind          QuestionKind `json:"kind"`
	Prompt        string       `json:"prompt"`
	Marks         int32        `json:"marks"`
	Position      int32        `json:"position"`
}

type Session struct {
	ID            int64              `json:"id"`
	InstitutionID int64              `json:"institution_id"`
	UserID        int64              `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	CreatedAt     time.Time          `json:"created_at"`
	LastSeenAt    time.Time          `json:"last_seen_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

// Transport state for SMS. Holds what was asked, not what was answered -- answers live in learning_events.
type SmsConversation struct {
	ID                  int64                `json:"id"`
	InstitutionID       int64                `json:"institution_id"`
	LearnerID           int64                `json:"learner_id"`
	State               SmsConversationState `json:"state"`
	PendingAssessmentID *int64               `json:"pending_assessment_id"`
	PendingQuestionID   *int64               `json:"pending_question_id"`
	PendingLessonID     *int64               `json:"pending_lesson_id"`
	PendingPosition     int32                `json:"pending_position"`
	PendingTotal        int32                `json:"pending_total"`
	OptedOut            bool                 `json:"opted_out"`
	CreatedAt           time.Time            `json:"created_at"`
	UpdatedAt           time.Time            `json:"updated_at"`
	LastMessageAt       pgtype.Timestamptz   `json:"last_message_at"`
}

type User struct {
	ID            int64     `json:"id"`
	InstitutionID int64     `json:"institution_id"`
	Email         string    `json:"email"`
	DisplayName   string    `json:"display_name"`
	Role          UserRole  `json:"role"`
	PasswordHash  *string   `json:"password_hash"`
	Msisdn        *string   `json:"msisdn"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
