// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOutboxRows = `-- name: ClaimDueOutboxRows :many

SELECT
    id,
    institution_id,
    event_id,
    topic,
    payload,
    destination_msisdn,
    created_at,
    attempts
FROM outbox
WHERE delivered_at IS NULL
  AND dead_at IS NULL
  AND destination_msisdn IS NOT NULL
  AND next_attempt_at <= now()
  AND (claimed_at IS NULL OR claimed_at < now() - make_interval(secs => $1::int))
ORDER BY next_attempt_at, id
LIMIT $2::int
FOR UPDATE SKIP LOCKED
`

type ClaimDueOutboxRowsParams struct {
	StaleAfterSeconds int32 `json:"stale_after_seconds"`
	BatchSize         int32 `json:"batch_size"`
}

type ClaimDueOutboxRowsRow struct {
	ID                int64       `json:"id"`
	InstitutionID     int64       `json:"institution_id"`
	EventID           pgtype.UUID `json:"event_id"`
	Topic             string      `json:"topic"`
	Payload           []byte      `json:"payload"`
	DestinationMsisdn *string     `json:"destination_msisdn"`
	CreatedAt         time.Time   `json:"created_at"`
	Attempts          int32       `json:"attempts"`
}

// Outbox drain queries for the SMS worker.
//
// The worker is the first reader of the table written in milestone 1. It
// follows the transactional outbox pattern: rows are claimed with a short lock,
// attempted, then either marked delivered or released with a backoff.
// Takes a batch of messages that are due for a delivery attempt.
//
// FOR UPDATE SKIP LOCKED is what makes multiple workers safe. Without it two
// workers would read the same row and send the message twice -- and since SMS
// is a real cost per message, that is not an acceptable failure mode.
//
// A row is due when it is undelivered, not dead, and next_attempt_at has
// passed. A stale claim is reclaimable after `stale_after`: a worker killed
// mid-attempt must not strand its messages forever.
func (q *Queries) ClaimDueOutboxRows(ctx context.Context, arg ClaimDueOutboxRowsParams) ([]ClaimDueOutboxRowsRow, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxRows, arg.StaleAfterSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueOutboxRowsRow{}
	for rows.Next() {
		var i ClaimDueOutboxRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.EventID,
			&i.Topic,
			&i.Payload,
			&i.DestinationMsisdn,
			&i.CreatedAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOutboxRow = `-- name: ClaimOutboxRow :one
UPDATE outbox
SET claimed_at = now(),
    attempts = attempts + 1
WHERE id = $1
  AND delivered_at IS NULL
  AND dead_at IS NULL
RETURNING id, attempts
`

type ClaimOutboxRowRow struct {
	ID       int64 `json:"id"`
	Attempts int32 `json:"attempts"`
}

// Marks a single row claimed. Separate from ClaimDueOutboxRows so the lock is
// taken only after the batch is known, keeping the transaction short.
func (q *Queries) ClaimOutboxRow(ctx context.Context, id int64) (ClaimOutboxRowRow, error) {
	row := q.db.QueryRow(ctx, claimOutboxRow, id)
	var i ClaimOutboxRowRow
	err := row.Scan(&i.ID, &i.Attempts)
	return i, err
}

const countUndeliveredOutbox = `-- name: CountUndeliveredOutbox :one
SELECT
    count(*) FILTER (WHERE delivered_at IS NULL AND dead_at IS NULL) AS pending,
    count(*) FILTER (WHERE dead_at IS NOT NULL)                      AS dead
FROM outbox
`

type CountUndeliveredOutboxRow struct {
	Pending int64 `json:"pending"`
	Dead    int64 `json:"dead"`
}

// Used by the health endpoint to surface a backed-up queue.
func (q *Queries) CountUndeliveredOutbox(ctx context.Context) (CountUndeliveredOutboxRow, error) {
	row := q.db.QueryRow(ctx, countUndeliveredOutbox)
	var i CountUndeliveredOutboxRow
	err := row.Scan(&i.Pending, &i.Dead)
	return i, err
}

const getOutboxByProviderMessageID = `-- name: GetOutboxByProviderMessageID :one
SELECT id, delivered_at IS NOT NULL AS already_delivered
FROM outbox
WHERE provider_message_id = $1
`

type GetOutboxByProviderMessageIDRow struct {
	ID               int64       `json:"id"`
	AlreadyDelivered interface{} `json:"already_delivered"`
}

// Matches an inbound delivery report to the row that produced it. Some
// gateways report delivery long after the send, so this lookup may be the only
// way to tie the two together.
func (q *Queries) GetOutboxByProviderMessageID(ctx context.Context, providerMessageID *string) (GetOutboxByProviderMessageIDRow, error) {
	row := q.db.QueryRow(ctx, getOutboxByProviderMessageID, providerMessageID)
	var i GetOutboxByProviderMessageIDRow
	err := row.Scan(&i.ID, &i.AlreadyDelivered)
	return i, err
}

const getOutboxRow = `-- name: GetOutboxRow :one
SELECT
    id,
    topic,
    payload,
    destination_msisdn,
    attempts,
    delivered_at,
    dead_at,
    last_error
FROM outbox
WHERE id = $1
`

type GetOutboxRowRow struct {
	ID                int64              `json:"id"`
	Topic             string             `json:"topic"`
	Payload           []byte             `json:"payload"`
	DestinationMsisdn *string            `json:"destination_msisdn"`
	Attempts          int32              `json:"attempts"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	DeadAt            pgtype.Timestamptz `json:"dead_at"`
	LastError         *string            `json:"last_error"`
}

func (q *Queries) GetOutboxRow(ctx context.Context, id int64) (GetOutboxRowRow, error) {
	row := q.db.QueryRow(ctx, getOutboxRow, id)
	var i GetOutboxRowRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.DestinationMsisdn,
		&i.Attempts,
		&i.DeliveredAt,
		&i.DeadAt,
		&i.LastError,
	)
	return i, err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox
SET delivered_at = now(),
    provider_message_id = $2,
    last_error = NULL
WHERE id = $1
  AND delivered_at IS NULL
`

type MarkOutboxDeliveredParams struct {
	ID                int64   `json:"id"`
	ProviderMessageID *string `json:"provider_message_id"`
}

// Records a successful send along with the provider's own id, so a late
// delivery report can be matched back to this row.
//
// The provider id is nullable because the Sender interface does not surface
// one for every provider; when absent the row still records that it went out.
func (q *Queries) MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, arg.ID, arg.ProviderMessageID)
	return err
}

const releaseOutboxRow = `-- name: ReleaseOutboxRow :exec
UPDATE outbox
SET claimed_at = NULL,
    last_error = $2,
    next_attempt_at = $3,
    dead_at = $4
WHERE id = $1
  AND delivered_at IS NULL
`

type ReleaseOutboxRowParams struct {
	ID            int64              `json:"id"`
	LastError     *string            `json:"last_error"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	DeadAt        pgtype.Timestamptz `json:"dead_at"`
}

// Returns a failed message to the queue with a backoff.
//
// `next_attempt_at` is computed by the caller and passed in, so the backoff
// policy lives in Go where it is testable rather than being scattered across
// SQL.
//
// dead_at is passed as a nullable timestamptz rather than a boolean + now(), so
// codegen produces a plain pgtype.Timestamptz the caller can set to NULL
// explicitly. An unset dead_at is indistinguishable from "not dead", which is
// what makes the partial index on dead_at work.
//
// claimed_at is cleared so another worker can pick the row up immediately.
func (q *Queries) ReleaseOutboxRow(ctx context.Context, arg ReleaseOutboxRowParams) error {
	_, err := q.db.Exec(ctx, releaseOutboxRow,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.DeadAt,
	)
	return err
}

const requeueDeadOutbox = `-- name: RequeueDeadOutbox :execrows
UPDATE outbox
SET dead_at = NULL,
    claimed_at = NULL,
    next_attempt_at = now(),
    attempts = 0
WHERE id = $1 AND dead_at IS NOT NULL
`

// Operator action: put dead messages back in the queue after investigating.
// Not exposed over HTTP yet; it is destructive and deserves a deliberate UI.
func (q *Queries) RequeueDeadOutbox(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, requeueDeadOutbox, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
