// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Applies one graded answer to an assessment's running totals.
	//
	// Guarded against double counting: the caller only reaches this query when
	// InsertLearningEvent actually inserted a row, so a replayed event never gets
	// here twice.
	//
	// The correct count is recomputed from distinct answered questions rather than
	// incremented, which keeps the projection consistent even if a learner
	// re-answers the same question through a second device.
	ApplyAnswerToProgress(ctx context.Context, arg ApplyAnswerToProgressParams) (ApplyAnswerToProgressRow, error)
	// Written in the same transaction as the event, so state and notification
	// cannot diverge. Nothing reads this table until milestone 2.
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (int64, error)
	GetAssessmentProgress(ctx context.Context, arg GetAssessmentProgressParams) (GetAssessmentProgressRow, error)
	GetAssessmentWithQuestions(ctx context.Context, arg GetAssessmentWithQuestionsParams) ([]GetAssessmentWithQuestionsRow, error)
	// Returns the choice matching a label, used to grade a submitted answer.
	GetChoiceForQuestion(ctx context.Context, arg GetChoiceForQuestionParams) (GetChoiceForQuestionRow, error)
	GetCourse(ctx context.Context, arg GetCourseParams) (GetCourseRow, error)
	// Lesson totals and mark totals are computed in independent LATERAL
	// subqueries on purpose.
	//
	// Joining lessons and assessment-progress rows into one FROM clause multiplies
	// rows: with three lessons and three assessments, each lesson row would carry
	// the assessment totals three times and the SUM would triple. Subqueries keep
	// each total independent.
	GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) ([]GetCourseProgressRow, error)
	GetInstitutionByID(ctx context.Context, id int64) (GetInstitutionByIDRow, error)
	GetInstitutionBySlug(ctx context.Context, slug string) (GetInstitutionBySlugRow, error)
	// Which label the learner submitted for a question, used to render a
	// previously-answered state.
	GetLearnerAnswer(ctx context.Context, arg GetLearnerAnswerParams) (GetLearnerAnswerRow, error)
	GetLearnerMSISDN(ctx context.Context, arg GetLearnerMSISDNParams) (*string, error)
	GetLesson(ctx context.Context, arg GetLessonParams) (GetLessonRow, error)
	GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (GetLessonProgressRow, error)
	GetQuestionMarks(ctx context.Context, arg GetQuestionMarksParams) (GetQuestionMarksRow, error)
	// Neo Learn read queries.
	//
	// Every query is institution-scoped. There is no query in this file that
	// filters on institution_id from the caller, because forgetting to do so is
	// a cross-tenant data leak.
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error)
	// Learning event ingest and progress projection.
	//
	// The idempotency guarantee lives in InsertLearningEvent's ON CONFLICT
	// DO NOTHING. InsertEvent returns the row only when it was actually written,
	// so the caller can skip projection work for a duplicate -- which is what
	// makes a learner who texts the same answer twice score it once.
	InsertLearningEvent(ctx context.Context, arg InsertLearningEventParams) (InsertLearningEventRow, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error)
	IsEnrolled(ctx context.Context, arg IsEnrolledParams) (bool, error)
	ListAssessmentsForCourse(ctx context.Context, arg ListAssessmentsForCourseParams) ([]ListAssessmentsForCourseRow, error)
	// is_correct is projected but the HTTP layer must never send it to a learner
	// before submission. See httpapi.writeProgress.
	ListChoicesForAssessment(ctx context.Context, arg ListChoicesForAssessmentParams) ([]ListChoicesForAssessmentRow, error)
	ListEnrolledCourses(ctx context.Context, arg ListEnrolledCoursesParams) ([]ListEnrolledCoursesRow, error)
	// Returns one flat, ordered list; the service groups it in memory. A flat
	// query avoids the row-multiplication a nested rows.Cursor would produce
	// across the modules/lessons cross product.
	ListModulesWithLessons(ctx context.Context, arg ListModulesWithLessonsParams) ([]ListModulesWithLessonsRow, error)
	RevokeSession(ctx context.Context, tokenHash string) error
	// Records activity for audit. Best-effort: a failure to update this row must
	// never fail a login.
	TouchSession(ctx context.Context, tokenHash string) error
	// Used to transparently upgrade a hash when the argon2 cost parameters are
	// raised. Scoped by institution so a user id cannot be used to reach across
	// tenants.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	// Ensures a progress row exists and returns it.
	//
	// institution_id and course_id are derived from the lesson rather than
	// supplied by the caller: a client must not be able to record progress
	// against a course it does not own, and the learner should not have to know
	// the course id to complete a lesson.
	UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (UpsertLessonProgressRow, error)
}

var _ Querier = (*Queries)(nil)
