// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSmsConversation = `-- name: CloseSmsConversation :exec
UPDATE sms_conversations
SET state = $3,
    pending_assessment_id = NULL,
    pending_question_id = NULL,
    pending_lesson_id = NULL,
    pending_position = 0,
    pending_total = 0,
    updated_at = now()
WHERE institution_id = $1
  AND learner_id = $2
`

type CloseSmsConversationParams struct {
	InstitutionID int64                `json:"institution_id"`
	LearnerID     int64                `json:"learner_id"`
	State         SmsConversationState `json:"state"`
}

// Returns a conversation to idle, clearing the pending target.
//
// The CHECK constraint requires the pending columns to be NULL in the idle and
// completed states, so this cannot be done by updating state alone.
func (q *Queries) CloseSmsConversation(ctx context.Context, arg CloseSmsConversationParams) error {
	_, err := q.db.Exec(ctx, closeSmsConversation, arg.InstitutionID, arg.LearnerID, arg.State)
	return err
}

const countCorrectAnswers = `-- name: CountCorrectAnswers :one
SELECT
    count(q.id) AS total,
    count(q.id) FILTER (WHERE answered.question_id IS NOT NULL) AS correct
FROM questions q
LEFT JOIN LATERAL (
    SELECT DISTINCT ON (ev.question_id) ev.question_id
    FROM learning_events ev
    JOIN choices ch
      ON ch.question_id = ev.question_id
     AND ch.label = ev.payload ->> 'choice_label'
    WHERE ev.learner_id = $2::bigint
      AND ev.question_id = q.id
      AND ev.kind = 'question_answered'
      AND ch.is_correct
    ORDER BY ev.question_id, ev.occurred_at DESC, ev.id DESC
) answered ON true
WHERE q.assessment_id = $1
`

type CountCorrectAnswersParams struct {
	AssessmentID int64 `json:"assessment_id"`
	LearnerID    int64 `json:"learner_id"`
}

type CountCorrectAnswersRow struct {
	Total   int64 `json:"total"`
	Correct int64 `json:"correct"`
}

// Used to decide whether an assessment is finished: every question answered
// correctly, not merely attempted.
func (q *Queries) CountCorrectAnswers(ctx context.Context, arg CountCorrectAnswersParams) (CountCorrectAnswersRow, error) {
	row := q.db.QueryRow(ctx, countCorrectAnswers, arg.AssessmentID, arg.LearnerID)
	var i CountCorrectAnswersRow
	err := row.Scan(&i.Total, &i.Correct)
	return i, err
}

const countEnrolledWithMSISDN = `-- name: CountEnrolledWithMSISDN :one
SELECT count(*)
FROM course_enrollments ce
JOIN users u ON u.id = ce.learner_id
WHERE ce.institution_id = $1
  AND u.msisdn IS NOT NULL
  AND u.role = 'student'
`

// Used by the delivery scheduler to decide whether an SMS push is worth
// attempting for an enrolled learner.
func (q *Queries) CountEnrolledWithMSISDN(ctx context.Context, institutionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrolledWithMSISDN, institutionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssessmentForSms = `-- name: GetAssessmentForSms :one
SELECT
    a.id,
    a.title,
    a.description,
    a.sms_eligible,
    a.course_id,
    a.institution_id
FROM assessments a
WHERE a.id = $1
  AND a.institution_id = $2
  AND a.published = true
`

type GetAssessmentForSmsParams struct {
	ID            int64 `json:"id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetAssessmentForSmsRow struct {
	ID            int64  `json:"id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	SmsEligible   bool   `json:"sms_eligible"`
	CourseID      int64  `json:"course_id"`
	InstitutionID int64  `json:"institution_id"`
}

func (q *Queries) GetAssessmentForSms(ctx context.Context, arg GetAssessmentForSmsParams) (GetAssessmentForSmsRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentForSms, arg.ID, arg.InstitutionID)
	var i GetAssessmentForSmsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SmsEligible,
		&i.CourseID,
		&i.InstitutionID,
	)
	return i, err
}

const getCorrectChoiceLabel = `-- name: GetCorrectChoiceLabel :one
SELECT label
FROM choices
WHERE question_id = $1
  AND institution_id = $2
  AND is_correct
LIMIT 1
`

type GetCorrectChoiceLabelParams struct {
	QuestionID    int64 `json:"question_id"`
	InstitutionID int64 `json:"institution_id"`
}

// The correct answer for a question.
//
// Read only to explain an incorrect reply. This is never projected into a
// question prompt: doing so would put the answer key in the message the learner
// sees before answering.
func (q *Queries) GetCorrectChoiceLabel(ctx context.Context, arg GetCorrectChoiceLabelParams) (string, error) {
	row := q.db.QueryRow(ctx, getCorrectChoiceLabel, arg.QuestionID, arg.InstitutionID)
	var label string
	err := row.Scan(&label)
	return label, err
}

const getFirstUnansweredLesson = `-- name: GetFirstUnansweredLesson :one
SELECT l.id, l.title, m.course_id
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE m.course_id = $1
  AND l.institution_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM progress p
      WHERE p.learner_id = $3
        AND p.lesson_id = l.id
        AND p.status = 'completed'
  )
ORDER BY m.position, l.position
LIMIT 1
`

type GetFirstUnansweredLessonParams struct {
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
	LearnerID     int64 `json:"learner_id"`
}

type GetFirstUnansweredLessonRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	CourseID int64  `json:"course_id"`
}

func (q *Queries) GetFirstUnansweredLesson(ctx context.Context, arg GetFirstUnansweredLessonParams) (GetFirstUnansweredLessonRow, error) {
	row := q.db.QueryRow(ctx, getFirstUnansweredLesson, arg.CourseID, arg.InstitutionID, arg.LearnerID)
	var i GetFirstUnansweredLessonRow
	err := row.Scan(&i.ID, &i.Title, &i.CourseID)
	return i, err
}

const getInstitutionsForMSISDN = `-- name: GetInstitutionsForMSISDN :many

SELECT DISTINCT institution_id
FROM users
WHERE msisdn = $1
  AND password_hash IS NOT NULL
ORDER BY institution_id
`

// SMS conversation and inbound-routing queries.
//
// Everything here exists to answer one question: a reply arrives carrying only
// a phone number and some text, and we have to work out what it means.
// Every institution a number is registered at.
//
// Returns a list rather than a single row on purpose. A human can legitimately
// be a learner at two schools, and silently picking one would let a reply be
// applied to the wrong tenant's records. The inbound path treats more than one
// row as unresolvable.
func (q *Queries) GetInstitutionsForMSISDN(ctx context.Context, msisdn *string) ([]int64, error) {
	rows, err := q.db.Query(ctx, getInstitutionsForMSISDN, msisdn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var institution_id int64
		if err := rows.Scan(&institution_id); err != nil {
			return nil, err
		}
		items = append(items, institution_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonForSms = `-- name: GetLessonForSms :one
SELECT
    l.id,
    l.title,
    l.body_markdown,
    l.sms_eligible,
    m.course_id,
    l.institution_id
FROM lessons l
JOIN modules m ON m.id = l.module_id
WHERE l.id = $1
  AND l.institution_id = $2
`

type GetLessonForSmsParams struct {
	ID            int64 `json:"id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetLessonForSmsRow struct {
	ID            int64  `json:"id"`
	Title         string `json:"title"`
	BodyMarkdown  string `json:"body_markdown"`
	SmsEligible   bool   `json:"sms_eligible"`
	CourseID      int64  `json:"course_id"`
	InstitutionID int64  `json:"institution_id"`
}

func (q *Queries) GetLessonForSms(ctx context.Context, arg GetLessonForSmsParams) (GetLessonForSmsRow, error) {
	row := q.db.QueryRow(ctx, getLessonForSms, arg.ID, arg.InstitutionID)
	var i GetLessonForSmsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.BodyMarkdown,
		&i.SmsEligible,
		&i.CourseID,
		&i.InstitutionID,
	)
	return i, err
}

const getNextUnansweredQuestion = `-- name: GetNextUnansweredQuestion :one
SELECT q.id, q.prompt, q.marks, q.position
FROM questions q
WHERE q.assessment_id = $1
  AND q.institution_id = $2
  AND q.position > $3
  AND NOT EXISTS (
      SELECT 1
      FROM learning_events ev
      JOIN choices ch
        ON ch.question_id = ev.question_id
       AND ch.label = ev.payload ->> 'choice_label'
      WHERE ev.learner_id = $4
        AND ev.question_id = q.id
        AND ev.kind = 'question_answered'
        AND ch.is_correct
  )
ORDER BY q.position
LIMIT $5::int
`

type GetNextUnansweredQuestionParams struct {
	AssessmentID  int64 `json:"assessment_id"`
	InstitutionID int64 `json:"institution_id"`
	Position      int32 `json:"position"`
	LearnerID     int64 `json:"learner_id"`
	Limit         int32 `json:"limit"`
}

type GetNextUnansweredQuestionRow struct {
	ID       int64  `json:"id"`
	Prompt   string `json:"prompt"`
	Marks    int32  `json:"marks"`
	Position int32  `json:"position"`
}

// Finds the question after `after_position` that the learner has not answered
// correctly yet.
//
// Correctly, not merely answered: a learner who answered wrong should see the
// question again with feedback rather than having it marked done. `limit` keeps
// the query cheap regardless of assessment size.
func (q *Queries) GetNextUnansweredQuestion(ctx context.Context, arg GetNextUnansweredQuestionParams) (GetNextUnansweredQuestionRow, error) {
	row := q.db.QueryRow(ctx, getNextUnansweredQuestion,
		arg.AssessmentID,
		arg.InstitutionID,
		arg.Position,
		arg.LearnerID,
		arg.Limit,
	)
	var i GetNextUnansweredQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Marks,
		&i.Position,
	)
	return i, err
}

const getQuestionForSms = `-- name: GetQuestionForSms :one
SELECT
    q.id,
    q.assessment_id,
    q.prompt,
    q.marks,
    q.position,
    a.title AS assessment_title,
    a.institution_id
FROM questions q
JOIN assessments a ON a.id = q.assessment_id
WHERE q.id = $1
  AND q.institution_id = $2
`

type GetQuestionForSmsParams struct {
	ID            int64 `json:"id"`
	InstitutionID int64 `json:"institution_id"`
}

type GetQuestionForSmsRow struct {
	ID              int64  `json:"id"`
	AssessmentID    int64  `json:"assessment_id"`
	Prompt          string `json:"prompt"`
	Marks           int32  `json:"marks"`
	Position        int32  `json:"position"`
	AssessmentTitle string `json:"assessment_title"`
	InstitutionID   int64  `json:"institution_id"`
}

// Fetches everything needed to render one question as text, including whether
// the learner already got it right.
func (q *Queries) GetQuestionForSms(ctx context.Context, arg GetQuestionForSmsParams) (GetQuestionForSmsRow, error) {
	row := q.db.QueryRow(ctx, getQuestionForSms, arg.ID, arg.InstitutionID)
	var i GetQuestionForSmsRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Prompt,
		&i.Marks,
		&i.Position,
		&i.AssessmentTitle,
		&i.InstitutionID,
	)
	return i, err
}

const getSmsConversation = `-- name: GetSmsConversation :one
SELECT
    id,
    institution_id,
    learner_id,
    state,
    pending_assessment_id,
    pending_question_id,
    pending_lesson_id,
    pending_position,
    pending_total,
    opted_out,
    last_message_at
FROM sms_conversations
WHERE institution_id = $1
  AND learner_id = $2
`

type GetSmsConversationParams struct {
	InstitutionID int64 `json:"institution_id"`
	LearnerID     int64 `json:"learner_id"`
}

type GetSmsConversationRow struct {
	ID                  int64                `json:"id"`
	InstitutionID       int64                `json:"institution_id"`
	LearnerID           int64                `json:"learner_id"`
	State               SmsConversationState `json:"state"`
	PendingAssessmentID *int64               `json:"pending_assessment_id"`
	PendingQuestionID   *int64               `json:"pending_question_id"`
	PendingLessonID     *int64               `json:"pending_lesson_id"`
	PendingPosition     int32                `json:"pending_position"`
	PendingTotal        int32                `json:"pending_total"`
	OptedOut            bool                 `json:"opted_out"`
	LastMessageAt       pgtype.Timestamptz   `json:"last_message_at"`
}

func (q *Queries) GetSmsConversation(ctx context.Context, arg GetSmsConversationParams) (GetSmsConversationRow, error) {
	row := q.db.QueryRow(ctx, getSmsConversation, arg.InstitutionID, arg.LearnerID)
	var i GetSmsConversationRow
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.LearnerID,
		&i.State,
		&i.PendingAssessmentID,
		&i.PendingQuestionID,
		&i.PendingLessonID,
		&i.PendingPosition,
		&i.PendingTotal,
		&i.OptedOut,
		&i.LastMessageAt,
	)
	return i, err
}

const getUserByMSISDN = `-- name: GetUserByMSISDN :one
SELECT
    id,
    institution_id,
    display_name,
    msisdn
FROM users
WHERE msisdn = $1
  AND institution_id = $2
  AND password_hash IS NOT NULL
LIMIT 1
`

type GetUserByMSISDNParams struct {
	Msisdn        *string `json:"msisdn"`
	InstitutionID int64   `json:"institution_id"`
}

type GetUserByMSISDNRow struct {
	ID            int64   `json:"id"`
	InstitutionID int64   `json:"institution_id"`
	DisplayName   string  `json:"display_name"`
	Msisdn        *string `json:"msisdn"`
}

// Inbound routing: turns the sender number into a learner.
//
// Scoped by institution because the same human can be a student at two
// schools, and an answer must be applied to the right one. The caller learns
// the institution from the sender id the gateway was configured with, not from
// anything the message body contains.
func (q *Queries) GetUserByMSISDN(ctx context.Context, arg GetUserByMSISDNParams) (GetUserByMSISDNRow, error) {
	row := q.db.QueryRow(ctx, getUserByMSISDN, arg.Msisdn, arg.InstitutionID)
	var i GetUserByMSISDNRow
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.DisplayName,
		&i.Msisdn,
	)
	return i, err
}

const listAssessmentsForSms = `-- name: ListAssessmentsForSms :many
SELECT
    a.id,
    a.title,
    a.position
FROM assessments a
WHERE a.course_id = $1
  AND a.institution_id = $2
  AND a.published = true
  AND a.sms_eligible = true
ORDER BY a.position
`

type ListAssessmentsForSmsParams struct {
	CourseID      int64 `json:"course_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListAssessmentsForSmsRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Position int32  `json:"position"`
}

// Assessments a learner can be messaged about. Used by the delivery scheduler
// to decide what to send next.
func (q *Queries) ListAssessmentsForSms(ctx context.Context, arg ListAssessmentsForSmsParams) ([]ListAssessmentsForSmsRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentsForSms, arg.CourseID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssessmentsForSmsRow{}
	for rows.Next() {
		var i ListAssessmentsForSmsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChoicesForSms = `-- name: ListChoicesForSms :many
SELECT label, body
FROM choices
WHERE question_id = $1
  AND institution_id = $2
ORDER BY position
`

type ListChoicesForSmsParams struct {
	QuestionID    int64 `json:"question_id"`
	InstitutionID int64 `json:"institution_id"`
}

type ListChoicesForSmsRow struct {
	Label string `json:"label"`
	Body  string `json:"body"`
}

// Returns every choice with its label and body. Whether one is correct is
// resolved server-side by the learning engine, never here: the rendering layer
// must not be able to leak the answer key into a message.
func (q *Queries) ListChoicesForSms(ctx context.Context, arg ListChoicesForSmsParams) ([]ListChoicesForSmsRow, error) {
	rows, err := q.db.Query(ctx, listChoicesForSms, arg.QuestionID, arg.InstitutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChoicesForSmsRow{}
	for rows.Next() {
		var i ListChoicesForSmsRow
		if err := rows.Scan(&i.Label, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSmsOptOut = `-- name: SetSmsOptOut :exec
UPDATE sms_conversations
SET opted_out = $3,
    state = CASE WHEN $3 THEN 'idle'::sms_conversation_state ELSE state END,
    pending_assessment_id = CASE WHEN $3 THEN NULL ELSE pending_assessment_id END,
    pending_question_id = CASE WHEN $3 THEN NULL ELSE pending_question_id END,
    pending_lesson_id = CASE WHEN $3 THEN NULL ELSE pending_lesson_id END,
    updated_at = now()
WHERE institution_id = $1
  AND learner_id = $2
`

type SetSmsOptOutParams struct {
	InstitutionID int64 `json:"institution_id"`
	LearnerID     int64 `json:"learner_id"`
	OptedOut      bool  `json:"opted_out"`
}

// Honours a STOP immediately. The inbound path checks this before sending
// anything, so opt-out takes effect on the next message rather than the next
// enrolment.
func (q *Queries) SetSmsOptOut(ctx context.Context, arg SetSmsOptOutParams) error {
	_, err := q.db.Exec(ctx, setSmsOptOut, arg.InstitutionID, arg.LearnerID, arg.OptedOut)
	return err
}

const upsertSmsConversation = `-- name: UpsertSmsConversation :one
INSERT INTO sms_conversations (
    institution_id,
    learner_id,
    state,
    pending_assessment_id,
    pending_question_id,
    pending_lesson_id,
    pending_position,
    pending_total,
    opted_out,
    last_message_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (institution_id, learner_id) DO UPDATE SET
    state = EXCLUDED.state,
    pending_assessment_id = EXCLUDED.pending_assessment_id,
    pending_question_id = EXCLUDED.pending_question_id,
    pending_lesson_id = EXCLUDED.pending_lesson_id,
    pending_position = EXCLUDED.pending_position,
    pending_total = EXCLUDED.pending_total,
    opted_out = EXCLUDED.opted_out,
    last_message_at = now(),
    updated_at = now()
RETURNING id, state, pending_assessment_id, pending_question_id,
          pending_lesson_id, pending_position, pending_total, opted_out
`

type UpsertSmsConversationParams struct {
	InstitutionID       int64                `json:"institution_id"`
	LearnerID           int64                `json:"learner_id"`
	State               SmsConversationState `json:"state"`
	PendingAssessmentID *int64               `json:"pending_assessment_id"`
	PendingQuestionID   *int64               `json:"pending_question_id"`
	PendingLessonID     *int64               `json:"pending_lesson_id"`
	PendingPosition     int32                `json:"pending_position"`
	PendingTotal        int32                `json:"pending_total"`
	OptedOut            bool                 `json:"opted_out"`
}

type UpsertSmsConversationRow struct {
	ID                  int64                `json:"id"`
	State               SmsConversationState `json:"state"`
	PendingAssessmentID *int64               `json:"pending_assessment_id"`
	PendingQuestionID   *int64               `json:"pending_question_id"`
	PendingLessonID     *int64               `json:"pending_lesson_id"`
	PendingPosition     int32                `json:"pending_position"`
	PendingTotal        int32                `json:"pending_total"`
	OptedOut            bool                 `json:"opted_out"`
}

// Creates or updates the conversation's pending target.
//
// ON CONFLICT covers the (institution_id, learner_id) unique index, so one
// conversation exists per learner per institution. pending_position and
// pending_total are refreshed because an assessment may be re-sent after new
// questions are added.
func (q *Queries) UpsertSmsConversation(ctx context.Context, arg UpsertSmsConversationParams) (UpsertSmsConversationRow, error) {
	row := q.db.QueryRow(ctx, upsertSmsConversation,
		arg.InstitutionID,
		arg.LearnerID,
		arg.State,
		arg.PendingAssessmentID,
		arg.PendingQuestionID,
		arg.PendingLessonID,
		arg.PendingPosition,
		arg.PendingTotal,
		arg.OptedOut,
	)
	var i UpsertSmsConversationRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.PendingAssessmentID,
		&i.PendingQuestionID,
		&i.PendingLessonID,
		&i.PendingPosition,
		&i.PendingTotal,
		&i.OptedOut,
	)
	return i, err
}
