// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const getInstitutionByID = `-- name: GetInstitutionByID :one
SELECT id, slug, name
FROM institutions
WHERE id = $1
`

type GetInstitutionByIDRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) GetInstitutionByID(ctx context.Context, id int64) (GetInstitutionByIDRow, error) {
	row := q.db.QueryRow(ctx, getInstitutionByID, id)
	var i GetInstitutionByIDRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getInstitutionBySlug = `-- name: GetInstitutionBySlug :one
SELECT id, slug, name
FROM institutions
WHERE slug = $1
`

type GetInstitutionBySlugRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) GetInstitutionBySlug(ctx context.Context, slug string) (GetInstitutionBySlugRow, error) {
	row := q.db.QueryRow(ctx, getInstitutionBySlug, slug)
	var i GetInstitutionBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT
    id,
    institution_id,
    email,
    display_name,
    role,
    password_hash
FROM users
WHERE institution_id = $1
  AND email = $2
`

type GetUserByEmailParams struct {
	InstitutionID int64  `json:"institution_id"`
	Email         string `json:"email"`
}

type GetUserByEmailRow struct {
	ID            int64    `json:"id"`
	InstitutionID int64    `json:"institution_id"`
	Email         string   `json:"email"`
	DisplayName   string   `json:"display_name"`
	Role          UserRole `json:"role"`
	PasswordHash  *string  `json:"password_hash"`
}

// Neo Learn read queries.
//
// Every query is institution-scoped. There is no query in this file that
// filters on institution_id from the caller, because forgetting to do so is
// a cross-tenant data leak.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.InstitutionID, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    institution_id,
    email,
    display_name,
    role
FROM users
WHERE institution_id = $1
  AND id = $2
`

type GetUserByIDParams struct {
	InstitutionID int64 `json:"institution_id"`
	ID            int64 `json:"id"`
}

type GetUserByIDRow struct {
	ID            int64    `json:"id"`
	InstitutionID int64    `json:"institution_id"`
	Email         string   `json:"email"`
	DisplayName   string   `json:"display_name"`
	Role          UserRole `json:"role"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.InstitutionID, arg.ID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (institution_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertSessionParams struct {
	InstitutionID int64     `json:"institution_id"`
	UserID        int64     `json:"user_id"`
	TokenHash     string    `json:"token_hash"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.InstitutionID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// Records activity for audit. Best-effort: a failure to update this row must
// never fail a login.
func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = $3,
    updated_at = now()
WHERE id = $2
  AND institution_id = $1
`

type UpdatePasswordHashParams struct {
	InstitutionID int64   `json:"institution_id"`
	ID            int64   `json:"id"`
	PasswordHash  *string `json:"password_hash"`
}

// Used to transparently upgrade a hash when the argon2 cost parameters are
// raised. Scoped by institution so a user id cannot be used to reach across
// tenants.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.InstitutionID, arg.ID, arg.PasswordHash)
	return err
}
